###
POST http://127.0.0.1:8000/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjU2NDQ5NH0.4-yAXsN_g0L2sUIqcjJgv7117-1cOtLWO6OOo3N38Bw

{
    "name": "Avengers: Infinity War",
    "description": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_UX477_CR0,0,477,268_AL_.jpg",
    "duration": "149",
    "genre": "Action, Adventure, Sci-Fi"
}

###
PUT http://127.0.0.1:8000/movie/391813cb-bfe6-4a18-9d37-d46e6875c794
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjU0MzM0Mn0.BfKuWPgf4f9dru43MQ4WydnIVNkEmoaU70ryEmC8p48

{
    "name": "Avengers: Infinity War Updated"
}

###
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "wK7OZ@example.com",
    "password": "password"
}

###
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "hola@example.com",
    "password": "password"
}

###
POST http://127.0.0.1:8000/auth/token
Content-Type: application/x-www-form-urlencoded

username=wK7OZ@example.com&password=password

###
POST http://127.0.0.1:8000/auth/token
Content-Type: application/x-www-form-urlencoded

username=hola@example.com&password=password

###
POST http://127.0.0.1:8000/auth/token
Content-Type: application/x-www-form-urlencoded

username=admin@example.com&password=admin123

###
GET http://127.0.0.1:8000/movie

###
POST http://127.0.0.1:8000/auditorium
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjU2NDQ5NH0.4-yAXsN_g0L2sUIqcjJgv7117-1cOtLWO6OOo3N38Bw

{
    "number": "1",
    "seats": 100,
    "rows": 10,
    "columns": 10
}

###
POST http://127.0.0.1:8000/showtime
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjU2NDQ5NH0.4-yAXsN_g0L2sUIqcjJgv7117-1cOtLWO6OOo3N38Bw

{
    "start_time": "2024-05-20 12:00",
    "movie_id": "2469b1ec-436f-41f1-a587-2d09c5c94b12",
    "auditorium_id": "65f4230b-b3d3-4412-850e-b45ffd789411",
    "avaible_tickets": 0,
    "status": "active"
}

###
GET http://127.0.0.1:8000/showtime/b68956e7-e886-4a1a-925a-758a885e28e8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjU2NDQ5NH0.4-yAXsN_g0L2sUIqcjJgv7117-1cOtLWO6OOo3N38Bw

###
POST http://127.0.0.1:8000/reservation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3SzdPWkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjU1ODg5OX0.Kjax4UplX23_oYQuk_pVFdHcIelCKWFaU3KJAebvntQ

{
    "amount": 2,
    "showtime_id": "bdc861a3-000f-4e95-ba2c-57e6bdc26837",
    "seats_list": [
        "A5",
        "A6"
    ]
}

###
GET http://127.0.0.1:8000/reservation