###
POST http://127.0.0.1:8000/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3SzdPWkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjE5NjcyNH0.akEGd-OArODK9Lf_BonRyhaImJtKwQ1FXUKamAFQxEE

{
    "name": "Avengers: Infinity War",
    "description": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_UX477_CR0,0,477,268_AL_.jpg",
    "duration": "149",
    "genre": "Action, Adventure, Sci-Fi"
}

###
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "wK7OZ@example.com",
    "password": "password",
    "role": "admin"
}

###
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "hola@example.com",
    "password": "password",
    "role": "user"
}

###
POST http://127.0.0.1:8000/auth/token
Content-Type: application/x-www-form-urlencoded

username=wK7OZ@example.com&password=password

###
POST http://127.0.0.1:8000/auth/token
Content-Type: application/x-www-form-urlencoded

username=hola@example.com&password=password

###
GET http://127.0.0.1:8000/movie

###
POST http://127.0.0.1:8000/auditorium
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3SzdPWkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjE5NjcyNH0.akEGd-OArODK9Lf_BonRyhaImJtKwQ1FXUKamAFQxEE

{
    "number": "1",
    "seats": 100,
    "rows": 10,
    "columns": 10
}

###
POST http://127.0.0.1:8000/showtime
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3SzdPWkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjE5NjcyNH0.akEGd-OArODK9Lf_BonRyhaImJtKwQ1FXUKamAFQxEE

{
    "start_time": "2020-01-01 12:00",
    "movie_id": "a60ed613-f7ca-46e8-95df-62f0b4d05231",
    "auditorium_id": "84b012c8-0ef3-4fe9-835d-7b3c605315cf",
    "avaible_tickets": 0,
    "status": "active"
}

###
GET http://127.0.0.1:8000/showtime

###
POST http://127.0.0.1:8000/reservation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJob2xhQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ2MTk2Nzc5fQ.0btkWfa-RleqiLf7ZYnCubrt7nvOpM_J_XsuAgpPAYo

{
    "amount": 2,
    "showtime_id": "0dcb0130-adee-4626-972d-281253db4d0c",
    "seats_list": [
        "A5",
        "A6"
    ]
}

###
GET http://127.0.0.1:8000/reservation